import React from 'react';
import "./terms.css";

const Terms = () => {
    return (
        <div className="terms-glass">
            <h1>Terms of Use</h1>
            <p>Please read the terms and conditions (“Terms of Use”)set out below carefully before ordering any Goods or usage of any Services from this site www.tasvee.in(hereinafter referred to as “Tasvee”).
                By browsing, accessing, subscribing to or using any of our services you agree that you have read, understood and are bound by the terms, regardless of how you subscribe to or use the services. By mere use of the website you shall be contracting with (“tasvee.in”).
                Tasvee reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the site following the posting of changes will mean that you accept and agree to the changes. As long as you comply with these terms, Tasvee grants you a personal, non-exclusive, non-transferable, limited privilege to access and use the website and services offered by Tasvee.
            </p>
            <h1>Section 1 : Introduction</h1>
            <p>We as Tasvee (www.tasvee.in) helps you book professional photographers for all events.</p>
            <h1>Section 2 : Definitions</h1>
            <p>2.1. “Agreement” is a reference to these Terms and Conditions, Terms of Use , Privacy Policy, any other form and payment instructions and any other kind of agreements provided to you;
                2.2. “Privacy Policy” means the policy displayed on our website which details with the collection, storage and use of personal data and other privacy issues;
                2.3. “you”, “your”,”user” and “yours” are references to you the person accessing this website and ordering any goods or services from the website or from any other channel provided by Tasvee;
                2.4. “we”, “us”, “our”, and ” Tasvee ” are references to the corporations, affiliates, and the officers, directors, employees and agents of these entities,;
                2.5. “Goods” is a reference to any goods which we may offer for sale from our website from time to time;
                2.6. “Service” or “Services” is a reference to any service which we may provide and which you may request via our website;
                2.7. “Affiliates (Photographers , Videographers,)” is a party, which has agreed to cooperate with the Tasvee to prepare and/or deliver the goods or services.
                2.8. “Delivery/services'' is a reference to goods/services ordered by you and is provided with any form of delivery/services service, the goods and service of the delivery/services of the goods are provided by our Affiliates(photographers and/or videographers)s and for both of which our Affiliates(photographers and/or videographers) take full responsibility; and
                2.9. “Website” is a reference to our website https:// www.tasvee.in</p>
            <h1>Section 3 : Ordering</h1>
            <p>
                3.1. Any contract for the supply of photography services from this website is between you and the Affiliates(photographers and/or videographers); for the order of Goods or Services from this Website any contact is between you and tasvee.in. You agree to take particular care when providing us with your details and warrant that these details are accurate and complete at the time of ordering. You also warrant that the credit or debit card details that you provide are of your own credit or debit card and that you have sufficient funds to make the payment.
                3.2. Photography services, goods and services purchased from this website are intended for your use only and you warrant that any goods purchased by you are not for resale and that you are acting as principal only and not as agent for another party when receiving the services.
                3.3. Please note that some of our goods may be suitable for certain age ranges only. You should check that the product you are ordering is suitable for the intended recipient.
                3.4. When ordering from this website you may be required to provide an e-mail address and password. You must ensure that you keep the combination of these details secure and do not provide this information to a third party.
                3.5. To keep the details of your order and payment secure, we will take all reasonable care, in so far as it is in our power to do so, but in the absence of negligence on our part we cannot be held liable for any loss you may suffer if a third party procures unauthorized access to any data you provide when accessing or ordering from the website.
                3.6. Any order that you place with us is subject to product availability, delivery/services capacity and acceptance by us and the Affiliates(photographers and/or videographers);. When you place your order online, we will send you an email to confirm that we have received it. This email confirmation will be produced automatically so that you have confirmation of your order details. You must inform us immediately if any details are incorrect. The fact that you receive an automatic confirmation does not necessarily mean that either we or the Affiliates(photographers and/or videographers); will be able to fill your order. Once we have sent the confirmation email we will check availability and delivery/services capacity.
                3.7. If the ordered goods and delivery/services/service capacity is available, the Affiliates(photographers and/or videographers); will accept the contract and confirm it to tasvee.in. If the details of the order are correct, the contract for the photography services, goods or services will be confirmed by text message (SMS) or mail , and call to the customer.
                3.8. The confirmation message will specify delivery/services/service details including the approximate delivery/services/service time specified by the Affiliates(photographers and/or videographers) and confirm the price of the services ordered.
                3.9. If the delivery/services, services and/or goods and/or affiliates are not available or if there is no delivery/services capacity, we will also let you know by text message (SMS) or phone call.
                3.10 Once an order is placed, and both the parties confirm the order (you and affiliates), you are not to cancel the order and should provide the complete payment for the goods and/or services ordered.
            </p>
            <h1>Section 4 : Prices and Payment</h1>
            <p>4.1. Any contract for the supply of delivery/services/services from this website is between you and the Affiliates(photographers and/or videographers); for the order of Goods or Services from this Website any contact is between you and tasvee.in. You agree to take particular care when providing us with your details and warrant that these details are accurate and complete at the time of ordering. You also warrant that the credit or debit card details that you provide are for your own credit or debit card and that you have sufficient funds to make the payment.
                4.2. All prices listed on the website are correct at the time of publication and have been input as received by the Affiliates; While we give great care to keep them up to date, the final price charged to you by the photographer/videographer can change at the time of delivery/services based on the prices of the Affiliate. We also reserve the right to alter the goods or services available for sale on the website and to stop listing photographers, videographers, studios, goods or services and any other kind of listing.
                4.3. All prices listed on the website for photography services delivery/services by the Affiliates(Photographers and/or videographers) or a delivery/services partner listed on the website reflect the price the Affiliates(Photographers and/or videographers) or the third party provider charges at the time of listing. In case the price listed is not current and the photographers and/or videographers inform us immediately after placing the order, we will put our best effort to contact you to inform you about the price difference and you can choose to opt-out of the order at that time.
                4.4. All prices for delivery/services by tasvee.in or a third party provider assigned by tasvee.in listed on the website are correct at the time of publication, however, we reserve the right to alter these in the future
                4.5. The total price for photography services, goods or services ordered, including delivery/services charges and other charges, will be displayed on the website when you place your order. Full payment must be made for all goods dispatched and services provided. Payment has to be made in cash or, if available on the website, by online payment, e.g. credit or debit card.
            </p>
            <h1>Section 5 : Delivery / services</h1>
            <p>5.1. Delivery/service periods quoted at the time of ordering are approximate and may vary. Goods will be delivered to the address designated by you at the time of ordering.
                5.2. The Delivery/services/service is provided by the Affiliates(Photographers and/or videographers) or its delivery/services partners, it is the Affiliates(Photographers and/or videographers)s or its delivery/services partner’s sole responsibility to provide photography services and delivery/services of goods in a timely manner.
                5.3. All orders are delivered by a reputable courier. The Affiliates(Photographers and/or videographers) will make every effort to deliver within the time stated, however, we will not be liable for any loss caused to you by ordering late. If the goods are not delivered within the estimated delivery/services time quoted by us, please contact the Affiliates(Photographers and/or videographers) first. You may also contact us by telephone or email and we will try to ensure that you receive your order/services as quickly as possible.
                5.4. If you fail to accept delivery/services of goods or/and services at the time they are ready for delivery/services, or we are unable to deliver at the nominated time due to your failure to provide appropriate instructions, or authorizations, then such good/services shall be deemed to have been delivered to you and all risk and responsibility in relation to such goods shall pass to you. Any transportation of affiliates, insurance and other costs which we incur as a result of the inability to deliver shall be your responsibility and you shall indemnify us in full for such cost.
                5.5. You must ensure that at the time of delivery/services of goods and/or services adequate arrangements, including access where necessary, are in place for the safe delivery/services of such goods/services. We cannot be held liable for any damage, cost or expense incurred to such goods or premises where this arises as a result of a failure to provide adequate access or arrangements for delivery/services/services.
                5.6. Affiliates(Photographers and/or videographers)s, aim
                5.6.1. to deliver the product/services to you at the place of delivery/services requested by you in your order;
                5.6.2. to deliver within the time confirmed by the you;
                5.6.3. to inform you if they expect that they are unable to meet the estimated delivery/services time.
            </p>

            <h1>Section 6 : Cancellation</h1>
            <p>6.1. Orders once placed and confirmed by you on www.tasvee.in cannot be cancelled.
                6.2. We may cancel a contract if the product/service/photographer/videographer is not available for any reason. We will notify you if this is the case and return any payment that you have made.
            </p>
            <h1>Section 7 : Intellectual Property Right</h1>
            <p>The website contains many valuable trademarks owned and used by Tasvee or and its subsidiaries, affiliates and related entities throughout the world. These trademarks are used to distinguish Tasvee’s quality services. These trademarks and related proprietary property are protected from reproduction and simulation under national and international laws and are not to be copied without the prior express written permission of Tasvee.
                The text, graphics and Tasvee’s html code (including graphic files and java script) contained in the website are the exclusive property of Tasvee, its affiliates or related entities. Except where otherwise noted, the text, graphics and html code contained here may not be copied, distributed, displayed, reproduced or transmitted in any form or by any means without the prior express written permission of Tasvee.
                The website may link to sites not maintained by or related to Tasvee. Hyper-text links are provided as a service to users and are not sponsored by or affiliated with this website or Tasvee. Tasvee has not reviewed the sites hyper-linked to or from this website and is not responsible for the content of any other site. These links are to be accessed at the user’s own risk. Tasvee makes no representations or warranties about the content, completeness, or accuracy of these links or the sites hyper-linked to this website. Furthermore, Tasvee does not implicitly endorse third-party sites hyper-linked to this website.
            </p>
            <h1>Section 8 : Information</h1>
            <p>8.1. Where we have requested information from you to provide Photography services, Goods or Services you agree to provide us with accurate and complete information.
                8.2. You authorize us to use, store or otherwise process your personal information in order to provide the photography services, goods or services to you and for marketing and credit control purposes. The purpose may include the disclosure of your personal information to selected third parties or the Affiliates from time to time where we believe that the services offered by such third parties or Affiliates may be of interest to you or where this is required by law or in order to provide the photography services, goods or service to you. More information can be found in our Privacy Policy.
                8.3. You are entitled to request a copy of the personal information we hold on you. Please contact us if you wish to request this information.
            </p>
            <h1>Section 9 : Linked Sites</h1>
            <p>There may be a number of links on our website to third party websites which we believe may be of interest to you. We do not represent the quality of the goods or services provided by such third parties nor do we have any control over the content or availability of such sites. We cannot accept any responsibility for the content of third party websites or the services or goods that they may provide to you.</p>
            <h1>Section 10 : Limitation of Liability</h1>
            <p>10.1. Great care has been taken to ensure that the information available on this website is correct and error free. We apologize for any errors or omissions that may have occurred. We cannot warrant that use of the website will be error free or fit for purpose, timely, that defects will be corrected, or that the site or the server that makes it available are free of viruses or bugs or represents the full functionality, accuracy, reliability of the website and we do not make any warranty whatsoever, whether express or implied, relating to fitness for purpose, or accuracy.
                10.2. By accepting these terms of use you agree to relieve us or any corporations, affiliates, and the officers, directors, employees and agents of this entities, from any liability whatsoever arising from your use of information from any third party, or your use of any third party website, or your acceptance of services from a Affiliates(Photographers and/or videographers).
                10.3. We disclaim any and all liability to you for the supply of the photography services, goods and services to the fullest extent permissible under applicable law. This does not affect your statutory rights as a consumer. If we are found liable for any loss or damage to you such liability is limited to the amount you have paid for the relevant goods or services. We cannot accept any liability for any loss, damage or expense, including any direct or indirect loss such as loss of profits to you, however arising.
                10.4. We do not accept any liability for any delays, failures, errors or omissions or loss of transmitted information, viruses or other contamination or destructive properties transmitted to you or your computer system via our Website.
                10.5. We shall not be held liable for any failure or delay in performing services or delivering goods/services where such failure arises as a result of any act or omission, which is outside our reasonable control such as an act of God or those of third parties.
                10.6. If we have contracted to provide identical or similar orders to more than one customer and are prevented from fully meeting our obligations to you by reason of an event of Force Majeure, we may decide at our absolute discretion which orders we will fill and to what extent.
                10.7. The products provided on our website are provided for private domestic and consumer use only. Accordingly, we do not accept liability for any indirect loss, consequential loss, loss of data, loss of income or profit, loss of damage to property and/or loss from claims of third parties arising out of the use of the website or for any products or services purchased from us.
                10.8. We have taken all reasonable steps to prevent internet fraud and ensure any data collected from you is stored as securely and safely as possible. However, we cannot be held liable in the extremely unlikely event of a breach in our secure computer servers or those of third parties.
                10.9 We do not take the liability of the description of the goods/services offered on the website,quality and the quantity of the goods/services offered. The liability of the same falls towards the Affiliate
                10.10 The liability of the delivery/services of the goods and/or photography services also falls only on the Affiliate and not Tasvee or its related enterprises.
                10.11 We are not to be held liable or deemed to be in default for any delay or failure in performance or interruption of the delivery/services of goods and/or photography services. Content resulting directly or indirectly from any cause or circumstance beyond its or their reasonable control, including but not limited to failure of electronic or mechanical equipment or communication lines, telephone or other interconnect problems, computer viruses, unauthorised access, theft, operator errors, severe weather, earthquakes or natural disasters, strikes or other labour problems, war, or governmental restrictions.</p>
            <h1>Section 11 : Ability to comprehend and accept the terms of use</h1>
            <p>By entering the website you affirm that you can completely comprehend and understand all the policies and other obligations, affirmations, representations, and warranties, and to abide by and comply with these Terms & Conditions of Use. The user also affirms that you are legally capable of using the website at its fullest.</p>
            <h1>Section 12 : General</h1>
            <p>11.1. All prices are in Indian Rupees.
                11.2. We may subcontract any part or parts of the services that we provide to you from time to time and we may assign any part or parts of our rights under these terms and conditions without your consent or any requirement to notify you.
                11.3. We may alter or vary the terms and conditions at any time without notice to you.
                11.4. Payment must be made either at the time of ordering the goods or services from us by credit card or by cash. Failure to pay on time will result in the cancellation of your order.
                11.5. Do not use or launch any automated system or program in connection with our website or its online ordering functionality;
                11.6. Do not collect or harvest any personally identifiable information from the website, use communication systems provided by the website for any commercial solicitation purposes, solicit for any reason whatsoever any users of the website with respect to their submissions to the website, or publish or distribute any vouchers or codes in connection with the website, or scrape or hack the website.
                11.7. The terms of use, privacy policy, order form and payment instructions constitute the entire agreement between you and us. No other terms whether expressed or implied shall form part of this agreement. In the event of any conflict between these terms of use and any other term or provision on the Website, these terms of use shall prevail.
                11.8. If any term or condition of our agreement shall be deemed invalid, illegal or unenforceable by the court the parties hereby agree that such term or condition shall be deemed to be deleted and the remainder of the agreement shall continue in force without such term or condition.
                11.9. These terms and conditions and our agreement shall be governed by and construed in accordance with the laws of India. The parties hereto submit to the exclusive jurisdiction of the courts of Pune court and Mumbai High court.
                11.10. No delay or failure on our part to enforce our rights or remedies under the agreement shall constitute a waiver on our part of such rights or remedies unless such waiver is confirmed in writing.</p>
            <h1>Section 12 : Complaints</h1>
            <p>We take complaints very seriously and aim to respond to your complaints within 5 business days. All complaints should be addressed to officialtasvee@gmail.com
            </p>
        </div>
    )
}

export default Terms